### PR TITLE
JL1.0 compatibility

### PR DESCRIPTION
**Pull request by joelostblom**
I looked at a couple of other plugins and made similar changes. I haven't worked with JL extensions before, so not sure if this is comprehensive, but it works for me.

### CODE REVIEW

**Comment by Rahlir** [comment]
Thanks! I will have a look at it this week!

**Comment by flxai** [comment]
@Rahlir I hope you will find time soon to merge this. Alternatively, is there a way to install @joelostblom 's fork? Is there a way to use a GitHub repository when using `jupyter labextension install [...]` instead of an npm package hosted on the official registry?

**Comment by Rahlir** [comment]
Sorry, I have a big test this Saturday, I will have a look right after. Sorry for the delay, I just wanted to update my JupyterLab and ensure everything works before merging and didn't get to it yet.

**Comment by flxai** [comment]
Looking forward to it. Good luck on your test.

**Comment by braun-steven** [comment]
@icks for the meantime:
```
git clone https://github.com/joelostblom/theme-gruvbox -b jl1.0-compat
cd theme-gruvbox
npm install
jupyter labextension link .
```

**Comment by Rahlir** [comment]
Sorry this took a while, the changes were actually simple enough. Thanks to @joelostblom!

**Comment by lukasbindreiter** [comment]
Leaving a comment here since it is somewhat related (and I can't seem to create an issue here in this repository): Do you think you could upgrade the package again to provide compatability with JupyterLab 2?

I'm not sure exactly but maybe a rebase on the latest commit of https://github.com/telamonian/theme-darcula would actually be enough already, since it was already updated to Jupyterlab 2: https://github.com/telamonian/theme-darcula/pull/14

**Pull request merged**
