### PR TITLE
Made it compatible with jupyterlab 1.x

### PR DESCRIPTION
**Pull request by lemeb**
That's it! Have a great day :)

### CODE REVIEW

**Comment by lemeb** [comment]
actually, it does break a few things in v 1.0.

there were a few changes to icons in jupyter lab 1.0:
`Update many of the icons to make them more consistent (#6672, #6618, #6664, #6621)`
and it shows...

**Comment by lemeb** [comment]
Ok, so I did add the missing icons. I am pretty sure none of them are missing, but, in the mean time, they are not "yellow-ized" as you would want to have a functional theme. But I figured you were the professional, so I kept the original new icons intact.

**Comment by Rahlir** [comment]
Thank you! There is a second pull request for this open now. I will have a look at both PRs this week and make the theme compatible with Jupyter Lab 1.0 ASAP.

**Comment by lemeb** [comment]
thanks! i know, now that i’ve used it for several days, that there still seems to be a couple of missing icons. i don’t know that i have the time to update it today, but i’ll try to handle that before you merge any changes.

**Pull request closed without merging**
